---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name:  ubuntu-14.04-chef
  driver_config:
    box: ubuntu-14.04
    box_url: file:///root/boxes/ubuntu

- name: centos6.5
  driver_config:
    box: centos-6.5-chef
    box_url: file:///root/boxes/centos

suites:
- name: java8
  run_list:
  - recipe[java-wrapper::java8]
  data_bags_path: ./data_bags