---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name:  ubuntu14.04
  driver_config:
    box: chef/ubuntu-14.04
    box_url: file:///root/boxes/ubuntu

- name: centos6.5
  driver_config:
    box: chef/centos-6.5
    box_url: file:///root/boxes/centos

suites:
- name: java8
  run_list:
  - recipe[java-wrapper::java8]
  data_bags_path: ./data_bags