---
driver_plugin: ssh

provisioner:
  name: chef_zero

platforms:
- name:  redhat65
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.102.108
- name:  redhat61
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.102.3
- name:  solaris112
  driver_config:
    hostname: 172.29.101.64
    username: root
    password: alfresco1
- name:  suse113
  driver_config:
    hostname: 172.29.102.169
    username: root
    password: alfresco
- name:  win2012
  driver_config:
    hostname: 172.29.102.12
    port: 5985
    username: 'Administrator'
    password: 'alfresco'
- name:  win2008
  driver_config:
    hostname: 172.29.102.10
    port: 5985
    username: Administrator
    password: alfresco

suites:
- name: postgres
  excludes:
    - solaris112
    - win2012
    - suse113
  run_list:
  - recipe[alfresco-dbwrapper::postgres]
  attributes: {
                url: {
                  postgresql: 'https://ftp.postgresql.org/pub/source/v9.4.5/postgresql-9.4.5.tar.gz',
                  package: 'postgresql-9.4.5'
                }
              }

- name: mysql
  excludes:
    - solaris112
    - win2012
    - suse113
  run_list:
  - recipe[alfresco-dbwrapper::mysql]

- name: mysql56
  excludes:
    - solaris112
    - win2012
    - suse113
  run_list:
  - recipe[alfresco-dbwrapper::mysql]
  attributes: {
                mysql: {
                  yum: {
                      version: 5.6.26-2.el7',
                      repository: 'http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm'
                    }
                }
              }


- name: oracle
  excludes:
    - win2012
    - suse113
  run_list:
  - recipe[alfresco-dbwrapper::oracle]
- name: mariadb
  excludes:
    - redhat65
    - solaris112
    - suse113
  run_list:
  - recipe[alfresco-dbwrapper::mariadb]
- name: sqlserver
  excludes:
    - redhat61
    - redhat65
    - solaris112
    - suse113
  run_list:
  - recipe[alfresco-dbwrapper::sqlserver]
  attributes: {
                sql_server: {
                  version: '2014'
                }
              }
- name: db2
  excludes:
    - redhat61
    - redhat65
    - solaris112
    - win2012
  run_list:
  - recipe[alfresco-dbwrapper::db2]
