---
driver_plugin: docker

provisioner:
  name: chef_zero

platforms:
- name: ubuntu
  driver_config:
    image: zuazo/chef-local:ubuntu-12.04
    platform: ubuntu
    use_cache: false

suites:
- name: schema2
  run_list:
  - recipe[alfresco-provisioning::schema2]
