---
driver_plugin: ssh

provisioner:
  name: chef_zero

platforms:
- name:  redhat65
  driver_config:
    port: 22
    username: root
    password: alfresco
    hostname: 172.29.101.52

suites:
- name: postgres
  run_list:
  - recipe[alfresco-dbwrapper::postgres]
  attributes: { localPath: false }