---
driver:
  name: vagrant
  customize:
    memory: 4096
provisioner:
  name: chef_zero

platforms:
- name:  ubuntu-14.04-chef
  driver_config:
    box: ubuntu-14.04-chef

suites:
- name: default
  run_list:
  - recipe[java-wrapper::java8]
  - recipe[alfresco-chef::installer]
#  - recipe[alfresco-chef::cfg-wqs]
  data_bags_path: ./data_bags
