---
driver_plugin: ssh

provisioner:
  name: chef_zero

platforms:
- name:  ubuntu1204
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.102.70
- name:  redhat65
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.101.52
- name:  solaris112
  driver_config:
    hostname: 172.29.101.64
    username: root
    password: alfresco1
- name:  win2012
  driver_config:
    hostname: 172.29.101.51
    port: 5985
    username: 'Administrator'
    password: 'alfresco'

suites:

- name: java8
  run_list:
  - recipe[java-wrapper::java8]

- name: java7
  run_list:
  - recipe[java-wrapper::java7]
