---
driver_plugin: ssh

provisioner:
  name: chef_zero

platforms:
- name:  ubuntu1204
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.101.46
- name:  redhat65
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.101.52
- name:  suse12
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.101.50
- name:  solaris112
  driver_config:
    hostname: 172.29.101.158
    username: root
    password: alfresco1
- name:  win2012
  driver_config:
    hostname: 172.29.101.51
    port: 5985
    username: Administrator
    password: alfresco
- name:  poc
  driver_config:
    hostname: 172.29.101.192
    username: root
    password: alfresco

suites:
- name: tomcat
  excludes:
    - suse12
    - redhat65
    - ubuntu1204
    - win2012
    - checklist
  run_list:
  - recipe[java-wrapper::java8]
  - recipe[chef-alfresco-installer::tomcat]
  attributes: { localPath: false }


- name: installer
  excludes:
    - solaris112
    - checklist
  run_list:
  - recipe[java-wrapper::java8]
  - recipe[chef-alfresco-installer::installer]
  attributes: {
                localPath: false,
                START_SERVICES: true,
                replication.enabled: false,
                alfresco.cluster.enabled: false,
                disable_solr_ssl: true,
                installer: {
                  disable-components: 'javaalfresco',
                  enable-components: 'alfrescowcmqs'
                  # downloadpath: 'https://releases.alfresco.com/Enterprise-4.2/4.2.4/PATCH-4.2.4.9/build-00127/ALL/alfresco-enterprise-4.2.4.9-installer-linux-x64.bin'
                }
              }

- name: replication
  excludes:
    - suse12
    - solaris112
    - ubuntu1204
    - win2012
    - checklist
  run_list:
  - recipe[chef-alfresco-installer::replication]
  attributes:
    localPath: false
    NFS_server: true
    dir_server: "/opt/ReplicateServer"

- name: replicationserver
  excludes:
    - suse12
    - solaris112
    - ubuntu1204
    - checklist
  run_list:
  - recipe[chef-alfresco-installer::replication_server]

- name: lbwin
  excludes:
    - suse12
    - solaris112
    - ubuntu1204
    - redhat65
    - checklist
  run_list:
  - recipe[chef-alfresco-installer::loadbalancer]

- name: poc
  excludes:
    - suse12
    - solaris112
    - ubuntu1204
    - redhat65
    - win2012
  run_list:
    - recipe[java-wrapper::java8]
    - recipe[chef-alfresco-installer::installer]
  attributes: {
                localPath: false,
                START_SERVICES: false,
                replication.enabled: false,
                alfresco.cluster.enabled: false,
                index.subsystem.name: 'solr',
                install_solr4_war: true,
                install_alfresco_war: false,
                install_share_war: false,
                installer: {
                  disable-components: 'javaalfresco',
                  enable-components: 'alfrescowcmqs',
                  downloadpath: 'ftp://172.29.101.56/50N/5.0.2/b34/alfresco-enterprise-5.0.2-installer-linux-x64.bin'
                }
              }
