---
driver_plugin: ssh

provisioner:
  name: chef_zero

platforms:
- name:  redhat65
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.101.52
- name:  solaris112
  driver_config:
    hostname: 172.29.101.64
    username: root
    password: alfresco1

suites:
- name: postgres
  excludes:
    - solaris112
  run_list:
  - recipe[alfresco-dbwrapper::postgres]
- name: mysql
  excludes:
    - solaris112
  run_list:
  - recipe[alfresco-dbwrapper::mysql]
- name: oracle
  excludes:
    - redhat65
  run_list:
  - recipe[alfresco-dbwrapper::oracle]