---
driver:
  name: vagrant
  synced_folders:
    - ["/resources", "/resources", "create: true"]

provisioner:
  name: chef_zero

platforms:
- name:  ubuntu-14.04
  driver_config:
    box: ubuntu-14.04-chef

#- name: centos6.5
#  driver_config:
#    box: centos-6.5-chef

suites:
- name: java8
  run_list:
  - recipe[java-wrapper::java8]
  attributes: { localPath: true }
  data_bags_path: ./data_bags
  encrypted_data_bag_secret_key_path: ./encrypted_data_bag_secret