---
driver_plugin: docker

provisioner:
  name: chef_zero

platforms:
- name: ubuntu
  driver_config:
    image: zuazo/chef-local:ubuntu-12.04
    platform: ubuntu
    use_cache: false

suites:
- name: schema2
  run_list:
  - recipe[alfresco-provisioning::default]
  attributes: {
                node1: '172.29.102.125',
                node2: '172.29.102.124',
                loadbalancer: '172.29.102.123'
              }
