---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name:  ubuntu14.04
  driver_config:
    box: chef/ubuntu-14.04
    box_url: https://atlas.hashicorp.com/chef/boxes/ubuntu-14.04

- name: centos6.5
  driver_config:
    box: chef/centos-6.5
    box_url: https://atlas.hashicorp.com/chef/boxes/centos-6.5

suites:
  - name: default
    data_bags_path: "/Users/p3700456/chef-repo/data_bags" 
    run_list:
    - recipe[java-wrapper::java8]