---
driver_plugin: ssh

provisioner:
  name: chef_zero

platforms:
- name:  ubuntu1204
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.101.46
- name:  redhat65
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.101.52
- name:  suse12
  driver_config:
    username: root
    password: alfresco
    hostname: 172.29.101.50
- name:  solaris112
  driver_config:
    hostname: 172.29.101.64
    username: root
    password: alfresco1
- name:  win2012
  driver_config:
    hostname: 172.29.101.51
    port: 5985
    username: Administrator
    password: alfresco

suites:
- name: tomcat
  excludes:
    - suse12
    - redhat65
    - ubuntu1204
    - win2012
  run_list:
  - recipe[java-wrapper::java8]
  - recipe[alfresco-chef::tomcat]
  attributes: { localPath: false }
- name: installer
  excludes:
    - solaris112
  run_list:
  - recipe[java-wrapper::java8]
  - recipe[alfresco-chef::installer]
  attributes: { localPath: false, START_SERVICES: true }

- name: replication
  excludes:
    - suse12
    - solaris112
    - ubuntu1204
    - win2012
  run_list:
  - recipe[alfresco-chef::replication]
  attributes: 
    localPath: false
    NFS_server: true
    dir_server: "/opt/ReplicateServer"

- name: replicationserver
  excludes:
    - suse12
    - solaris112
    - ubuntu1204
  run_list:
  - recipe[alfresco-chef::replication_server]
  attributes:
    replication_remote_ip: '172.29.101.110'

- name: lbwin
  excludes:
    - suse12
    - solaris112
    - ubuntu1204
    - redhat65
  run_list:
  - recipe[alfresco-chef::loadbalancer]




