---
driver_plugin: ssh
driver_config:
  port: 22
  password: <%= ENV['MPASS'] %>

provisioner:
  name: chef_zero

platforms:
- name:  ubuntu1204
  driver_config:
    username: root
    hostname: 172.29.101.46
- name:  redhat65
  driver_config:
    username: root
    hostname: 172.29.101.52
- name:  suse12
  driver_config:
    username: root
    hostname: 172.29.101.50
- name:  solaris112
  driver_config:
    hostname: 172.29.101.64
    username: root
    password: alfresco1

suites:
- name: tomcat
  excludes:
    - suse12
    - redhat65
    - ubuntu1204
  run_list:
  - recipe[java-wrapper::java8]
  - recipe[alfresco-chef::tomcat]
  attributes: { localPath: false }
- name: installer
  excludes:
    - solaris112
  run_list:
  - recipe[java-wrapper::java8]
  - recipe[alfresco-chef::installer]
  attributes: { localPath: false }
- name: installerwin
  excludes:
    - suse12
    - redhat65
    - solaris112
  attributes: { localPath: false }