
---
driver:
  name: ssh
  hostname: 172.29.100.131
  port: 22
  username: root

provisioner:
  name: chef_zero

platforms:
- name: ubuntu1404

suites:
  - name: java8
    run_list:
    - recipe[java-wrapper::java8]
    data_bags_path: ./data_bags