source 'https://rubygems.org'

# gem 'berkshelf', '~> 3.2.3'
# gem 'test-kitchen', '~> 1.4.0'
# gem 'cucumber', '~> 1.3.19'
# gem 'rspec-expectations', '~> 3.2.0'
# gem 'kitchen-ssh', '~> 0.0.8'
# gem 'winrm-transport', '~> 1.0'
gem 'rake', '~> 10.4.2'
gem 'rubocop', '~> 0.32.1'
gem 'foodcritic', '~> 5.0.0'
