name             'alfresco-metal'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures alfresco-metal'
long_description 'Installs/Configures alfresco-metal'
version          '0.1.0'
