---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  attributes:
    java:
      ark_retries: 2
      ark_retry_delay: 10

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    driver:
      box: box-cutter/ubuntu1404
    run_list:
    - recipe[apt]
  #- name: ubuntu-12.04
  #  driver:
  #    box: box-cutter/ubuntu1204
  #  run_list:
  #  - recipe[apt]
  - name: debian-6.0.10
    driver:
      box: box-cutter/debian6010
    run_list:
    - recipe[apt]
  - name: debian-7.6
    driver:
      box: box-cutter/debian76
    run_list:
    - recipe[apt]
  - name: centos-7.1
    driver:
      box: box-cutter/centos71
  - name: centos-6.5
    driver:
      box: box-cutter/centos65
  - name: centos-5.11
    driver:
      box: box-cutter/centos511
  - name: fedora-19
    driver:
      box: box-cutter/fedora19
  - name: fedora-20
    driver:
      box: box-cutter/fedora20

suites:
  - name: openjdk
    excludes:
      - fedora-19
      - fedora-20
    run_list:
      - recipe[java::default]
  - name: openjdk-7
    excludes:
      - ubuntu-10.04
      - debian-6.0.8
    run_list:
      - recipe[java::default]
    attributes:
      java:
        jdk_version: "7"
  - name: oracle
    run_list:
      - recipe[test_java::default]
      - recipe[java::default]
    attributes:
      java:
        oracle:
          accept_oracle_download_terms: true
          jce:
            enabled: true
        install_flavor: oracle
  - name: oracle-7
    run_list:
      - recipe[test_java::default]
      - recipe[java::default]
    attributes:
      java:
        jdk_version: "7"
        oracle:
          accept_oracle_download_terms: true
          jce:
            enabled: true
        install_flavor: oracle
  - name: oracle-8
    run_list:
      - recipe[test_java::default]
      - recipe[java::default]
    attributes:
      java:
        jdk_version: "8"
        oracle:
          accept_oracle_download_terms: true
          jce:
            enabled: true
        install_flavor: oracle
  - name: oracle-direct
    run_list:
      - recipe[java::oracle]
    attributes:
      java:
        oracle:
          accept_oracle_download_terms: true
  - name: openjdk-direct
    run_list:
      - recipe[java::openjdk]
    excludes:
      - fedora-19
      - fedora-20
  - name: oracle-rpm
    run_list:
      - recipe[java]
    attributes:
      java:
        install_flavor: oracle_rpm
        jdk_version: 7
        oracle:
          accept_oracle_download_terms: true
